spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_bet_engine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080
