spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_bet_engine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  threads:
    virtual:
      enabled: true

  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true

management:
  endpoints:
    web:
      exposure:
        include: health

betting:
  vig-rate: 0.05
  default-duration-seconds: 60

binance:
  ws-url: wss://stream.binance.com:9443/ws
  symbols: BTCUSDT,ETHUSDT

server:
  port: 8080
